# Generated by Django 3.1.2 on 2020-10-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201006_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='Ссылка на аватар пользователя'),
        ),
    ]
